### ISSUE TITLE
Allow user to configure the number of web workers

### ISSUE THREAD

**Issue by ferjm** [servo/buildbotstatus#1]
We are currently using a pool of [4 web workers](https://github.com/servo/buildbotstatus/blob/master/app/scripts/config.js#L2) to fetch all the builds data. We should expose a way to allow the users to customize this behavior from the UI.

The Buildbot API client already gets an [optional parameter](https://github.com/servo/buildbotstatus/blob/master/app/scripts/buildbot_client.js#L20) in its constructor to set the number of workers the client will use. And we [recreate a new client per each user request](https://github.com/servo/buildbotstatus/blob/master/app/scripts/ui.js#L45). So this should just be a matter of adding a select element to the UI, get its value before creating the client and disabling the UI element while the tool is performing the search.

**Comment by CYBAI** [comment]
@ferjm I'd like to try this one!

**Comment by ferjm** [comment]
@CYBAI great! Go for it. Thank you.
