### ISSUE TITLE
Create a gulp task to serve the content without watching for changes

### ISSUE THREAD

**Issue by ferjm** [servo/buildbotstatus#10]
#6 made the dev process easier by using browsersync. However if we ever deploy this tool somewhere we won't need to watch for changes. It would be nice to have a gulp task to serve the content without using browsersync.

@CYBAI do you want to give it a try?

**Comment by CYBAI** [comment]
@ferjm Yeah! I'd like to help this one!

How about changing the current `default` gulp task as `dev` and using `default` for deployment?

**Comment by ferjm** [comment]
Sounds good. Thank you!
