### ISSUE TITLE
Can we get an SSL certificate for build.servo.org?

### ISSUE THREAD

**Issue by ferjm** [servo/buildbotstatus#11]
Once we decide to deploy this tool to a server, we should ideally do it over HTTPS. Otherwise, the service worker and the cache introduced with #9 won't work. The problem with serving it over HTTPS is that any cross origin request to HTTP will be [blocked](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content) by the browser.

build.servo.org is currently served over insecure HTTP. Could we get an SSL certificate for it?

**Comment by jdm** [comment]
Getting an SSL certificate from letsencrypt should be straightforward. The trickier bit is ensuring that we have a scheduled task to renew it regularly. That requires writing a script to automate the process, then adding some crontab integration to our salt setup on servo-master1 using https://docs.saltstack.com/en/latest/ref/states/all/salt.states.cron.html.

**Comment by ferjm** [comment]
Thanks to @jdm https://build.servo.org works now :)
