### ISSUE TITLE
Enable gh-pages

### ISSUE THREAD

**Issue by ferjm** [servo/buildbotstatus#18]
I have created a `gh-pages` branch, but it seems that they are disabled for this repo. I don't have admin privileges, so I can't enable them. @jdm have you got admin privileges?

In the mean time, https://ferjm.github.io/buildbotstatus can be used.

**Comment by jdm** [comment]
Everything in the settings for servo/buildbotstatus suggests that it's set up to do github pages. I don't see any setting that would cause it to be disabled, so I'm a bit baffled.

**Comment by jdm** [comment]
Ok, once I changed the target branch to master and then back to gh-pages, it told me it is ready to be published. We probably need some kind of push to kick it off now.

**Comment by CYBAI** [comment]
@jdm It works now! 
https://servo.github.io/buildbotstatus/
