### ISSUE TITLE
Accept a URL parameter for the pull request

### ISSUE THREAD

**Issue by jdm** [servo/buildbotstatus#19]
If we load ?pull=1234, we could start fetching immediately without waiting for any input (or at least fill in the input box so it's easy to start). This would give us a nice way to add clickable links to PRs immediately when starting a build.

**Comment by ferjm** [comment]
This can be done by getting the query parameter during [UI initialization](https://github.com/servo/buildbotstatus/blob/master/app/scripts/ui.js#L8) and calling [getStatus](https://github.com/servo/buildbotstatus/blob/master/app/scripts/ui.js#L39) with the query parameter as argument.

**Comment by erickosamudera** [comment]
@highfive: assign me. Hi, I'm still very new to open source collaboration, and would like to try working on this issue.

**Comment by emilio** [comment]
Ouch, I just sorta-did something like this in #22, but I didn't realize #21 was open... I'll close mine.
