### ISSUE TITLE
Unnecessary scrollbar appears in firefox

### ISSUE THREAD

**Issue by jdm** [servo/buildbotstatus#20]
[This rule](https://github.com/servo/buildbotstatus/blob/7a68960706192e947d536d2b68659c416be495fc/app/styles/main.css#L9) doesn't seem to affect the layout of the page but does cause a scrollbar to appear unnecessarily when the page is first loaded.

**Comment by jhpratt** [comment]
@jdm Running the dev server, it makes a difference if you try to select the number of workers in the settings menu.

**Comment by stewy33** [comment]
I can work on this. @highfive: assign me
@jhpratt It doesn't seem to make a difference for me in Firefox, Chrome, or Opera. What exactly did you see, and under what environment?

**Comment by jdm** [comment]
@stewy33 Did you make any progress? :)
