### ISSUE TITLE
Add a github page

### ISSUE THREAD

**Issue by tigercosmos** [servo/buildbotstatus#24]
can read online

**Comment by CYBAI** [comment]
@tigercosmos Do you mean https://servo.github.io/buildbotstatus/ ?

**Comment by tigercosmos** [comment]
yes! but I cannot use it to search. the website show nothing. (seems need a server)
<img width="1430" alt="2018-04-13 10 52 36" src="https://user-images.githubusercontent.com/18013815/38714429-cc410642-3f08-11e8-81d6-e5657c8dd199.png">

**Comment by CYBAI** [comment]
@tigercosmos Hmm... we're using `https` for `buildbot` site but it seems that the `https` one cannot be accessed now; thus, it caused the failed fetch.

cc @jdm @ferjm 

https://github.com/servo/buildbotstatus/blob/0454bfee8880cd8b4cee24cc99c3ddfb74269b3a/app/scripts/config.js#L1

Note:
> http://build.servo.org/
Works

> https://build.servo.org/
Not work

**Comment by ferjm** [comment]
https://build.servo.org is back
